### ISSUE TITLE
[HOTFIX] QA 이후 할 것

### ISSUE THREAD

**Issue by MinwooP** [TeamCARDNA/Cardna-Android#111]
## 📝 구현할 사항

- [x] 카드 이미지 쓰이는 이미지 뷰 이미지 비율 유지되도록
- [x] 네이버 회원탈퇴가 잘 안됨
       => 네트워크 신호가 약해 실패했을 시 재로그인이 필요하므로 토스트메시지와 함께 로그인 액티비티로 이동 
- [x] 친구검색으로 들어가서 친구 카드팩 보면 친구 카드가 안보임
- [x] 친구 카드나 엠티뷰 구현 잘 되어 있는지 확인
- [x] 안드로이드 API Q미만 이미지 저장, 공유 
- [x] 앱 업데이트 로직
- [x] 서치 뷰 입력 커서 색깔 변경하기
- [x] 토큰 재발급 서버랑 맞춰보기
- [x] 카드 작성 시 심볼 아이디 변경

카드 작성 시
- [x] 내용 부분 줄바꿈 안되도록
       => 엔터키 누르면 키보드 숨김 동작으로 실행되도록 변경
- [x] 200자 끝까지 입력 시 마지막 줄 텍스트 짤려서 보임.
       =>  내용이 많아서 줄이 내려갈 때 스크롤 가능하도록 
- [x] 키보드 다음 버튼을 누르면 제목 텍스트 창  → 본문 텍스트 창으로 이동 가능하도록 
- [x] 카드 타이틀 입력 위한 터치 잘 안됨
       => "나는" 클릭 시 타이틀 입력 할 수 있도록 구현 
- [ ] 현재 이모티콘 입력시 2글자로 인식 됨 => 해결 불가😨
- [x] 제목, 내용 입력 시 입력 커서 만들기
- [x] 바텀 다이얼로그 빠르게 연속으로 두 번 클릭 시, 앱 터지는 오류 방지 위해 바텀 다이얼로그 한번만 띄워지도록 방지하는 코드 추가

**Comment by dabinKim-0318** [comment]
오 정리 좀 멋진데

**Comment by MinwooP** [comment]
> 오 정리 좀 멋진데

좀 ?
