### ISSUE TITLE
[HOTFIX] QA 이후에 할 것

### ISSUE THREAD

**Issue by dabinKim-0318** [TeamCARDNA/Cardna-Android#112]
## 📝 구현할 사항
- [x] 친구메인카드액티비티에서 가는 모든 활동 점검
- [x] 알림 이름 길어지면 end되도록
- [x] 신고 카테고리 누르면 다이얼로그 없어지고 아무 반응이 없음. "신고가 접수되었습니다" 떠야
- [x] 신고가 접수된 비공개 카드너는 바로 삭제 되는가? | FALSE | 신고 후, 다이얼로그 없어지고 다시 비공개 카드너 상세페이지로 감. 여기서 카드너 추가하기 누르면 "카드너가 추가됐어요 !" 로티 뜸. 근데 카드너로 생성은 안됨. 상세페이지 pop 해줘야 할듯
- [x] 친구 추가 버튼 터치 영역이 너무 좁은 듯. 친구 프로필로 자주 감
- [x] 선택할 때 체크 말고도 텍스트 선택해도 체크표시 되면 더욱 좋을 것 같아요 :) -> 대공사되어야해서 체크박스 영역넓힘

+ 로딩 로티

**Comment by MinwooP** [comment]
고생했도치
